#!/bin/bash
# scripts/docs/config_modules/config_mkdocs_main.sh
# Configuração principal do MkDocs com tema e plugins
# Neural Crypto Bot 2.0 Documentation System

# ================================
# CONFIGURAÇÃO PRINCIPAL DO MKDOCS
# ================================

config_mkdocs_main() {
    log_substep "Criando Configuração Principal do MkDocs"
    
    # Verificar se diretório docs existe
    if [[ ! -d "$DOCS_DIR" ]]; then
        log_error "Diretório docs não encontrado: $DOCS_DIR"
        return 1
    fi
    
    # Criar configuração principal
    cat > "$MKDOCS_CONFIG_FILE" << 'EOF'
# Neural Crypto Bot 2.0 - Enterprise Documentation Configuration
# Generated by Oasis Documentation System v2.0.0

site_name: Neural Crypto Bot 2.0 Documentation
site_description: >-
  Enterprise-grade cryptocurrency trading bot powered by advanced machine learning,
  microservices architecture, and quantitative finance algorithms.
site_author: Neural Crypto Bot Team
site_url: https://docs.neuralcryptobot.com

# Repository Configuration
repo_name: neural-crypto-bot/neural-crypto-bot-2.0
repo_url: https://github.com/neural-crypto-bot/neural-crypto-bot-2.0
edit_uri: edit/main/docs/

# Copyright and Legal
copyright: >
  Copyright &copy; 2024 Neural Crypto Bot Team –
  <a href="#__consent">Change cookie settings</a>

# Theme Configuration
theme:
  name: material
  custom_dir: docs/overrides
  
  # Branding
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  
  # Language and Locale
  language: en
  
  # Color Palette
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Typography
  font:
    text: Inter
    code: JetBrains Mono
  
  # Feature Flags
  features:
    # Announcements
    - announce.dismiss
    
    # Content
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    
    # Header
    - header.autohide
    
    # Navigation
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    
    # Search
    - search.highlight
    - search.share
    - search.suggest
    
    # Table of Contents
    - toc.follow
    - toc.integrate
  
  # Icons
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    logo: material/robot

# Navigation Structure
nav:
  - Home: index.md
  - Getting Started:
    - Overview: 01-getting-started/README.md
    - Quick Start: 01-getting-started/quickstart.md
    - Installation:
      - Overview: 01-getting-started/installation/README.md
      - Docker: 01-getting-started/installation/docker.md
      - Kubernetes: 01-getting-started/installation/kubernetes.md
      - Cloud Deployment:
        - AWS: 01-getting-started/installation/aws.md
        - GCP: 01-getting-started/installation/gcp.md
        - Azure: 01-getting-started/installation/azure.md
    - Configuration:
      - Overview: 01-getting-started/configuration/README.md
      - Environment: 01-getting-started/configuration/environment.md
      - Exchanges: 01-getting-started/configuration/exchanges.md
      - Strategies: 01-getting-started/configuration/strategies.md
      - Monitoring: 01-getting-started/configuration/monitoring.md
    - Troubleshooting:
      - Overview: 01-getting-started/troubleshooting/README.md
      - Common Issues: 01-getting-started/troubleshooting/common-issues.md
      - Performance: 01-getting-started/troubleshooting/performance.md
      - Debugging: 01-getting-started/troubleshooting/debugging.md
  
  - Architecture:
    - Overview: 02-architecture/README.md
    - System Design: 02-architecture/overview.md
    - Domain-Driven Design: 02-architecture/domain-driven-design.md
    - Microservices: 02-architecture/microservices.md
    - Data Flow: 02-architecture/data-flow.md
    - Components:
      - API Gateway: 02-architecture/components/api-gateway.md
      - Data Collector: 02-architecture/components/data-collector.md
      - Execution Engine: 02-architecture/components/execution-engine.md
      - Training Service: 02-architecture/components/training-service.md
      - Analytics Service: 02-architecture/components/analytics-service.md
      - Risk Management: 02-architecture/components/risk-management.md
    - Patterns:
      - CQRS & Event Sourcing: 02-architecture/patterns/cqrs-event-sourcing.md
      - Circuit Breaker: 02-architecture/patterns/circuit-breaker.md
      - Saga Pattern: 02-architecture/patterns/saga-pattern.md
      - Repository Pattern: 02-architecture/patterns/repository-pattern.md
    - Decision Records:
      - Overview: 02-architecture/decision-records/README.md
      - ADR-001 Architecture: 02-architecture/decision-records/adr-001-architecture.md
      - ADR-002 Database: 02-architecture/decision-records/adr-002-database.md
      - ADR-003 Messaging: 02-architecture/decision-records/adr-003-messaging.md
      - ADR-004 Deployment: 02-architecture/decision-records/adr-004-deployment.md
  
  - Development:
    - Overview: 03-development/README.md
    - Environment Setup: 03-development/setup.md
    - Coding Standards: 03-development/coding-standards.md
    - Testing:
      - Overview: 03-development/testing/README.md
      - Unit Testing: 03-development/testing/unit-testing.md
      - Integration Testing: 03-development/testing/integration-testing.md
      - E2E Testing: 03-development/testing/e2e-testing.md
      - Performance Testing: 03-development/testing/performance-testing.md
    - Debugging:
      - Overview: 03-development/debugging/README.md
      - Logging: 03-development/debugging/logging.md
      - Metrics: 03-development/debugging/metrics.md
      - Tracing: 03-development/debugging/tracing.md
    - CI/CD:
      - Overview: 03-development/ci-cd/README.md
      - GitHub Actions: 03-development/ci-cd/github-actions.md
      - Docker Builds: 03-development/ci-cd/docker-builds.md
      - Deployment Strategies: 03-development/ci-cd/deployment-strategies.md
    - Tools:
      - Overview: 03-development/tools/README.md
      - IDE Setup: 03-development/tools/ide-setup.md
      - Docker Compose: 03-development/tools/docker-compose.md
      - Makefile: 03-development/tools/makefile.md
  
  - Trading:
    - Overview: 04-trading/README.md
    - Strategies:
      - Overview: 04-trading/strategies/README.md
      - Momentum LSTM: 04-trading/strategies/momentum-lstm.md
      - Mean Reversion: 04-trading/strategies/mean-reversion.md
      - Arbitrage: 04-trading/strategies/arbitrage.md
      - Sentiment Analysis: 04-trading/strategies/sentiment-analysis.md
      - Custom Strategies: 04-trading/strategies/custom-strategies.md
      - Strategy Testing: 04-trading/strategies/strategy-testing.md
    - Risk Management:
      - Overview: 04-trading/risk-management/README.md
      - Position Sizing: 04-trading/risk-management/position-sizing.md
      - Stop Loss: 04-trading/risk-management/stop-loss.md
      - Drawdown Control: 04-trading/risk-management/drawdown-control.md
      - VaR Calculation: 04-trading/risk-management/var-calculation.md
      - Portfolio Optimization: 04-trading/risk-management/portfolio-optimization.md
    - Execution:
      - Overview: 04-trading/execution/README.md
      - Order Types: 04-trading/execution/order-types.md
      - Smart Routing: 04-trading/execution/smart-routing.md
      - Slippage Management: 04-trading/execution/slippage-management.md
      - Execution Algorithms: 04-trading/execution/execution-algorithms.md
    - Backtesting:
      - Overview: 04-trading/backtesting/README.md
      - Historical Data: 04-trading/backtesting/historical-data.md
      - Simulation Engine: 04-trading/backtesting/simulation-engine.md
      - Performance Metrics: 04-trading/backtesting/performance-metrics.md
  
  - Machine Learning:
    - Overview: 05-machine-learning/README.md
    - Models:
      - Overview: 05-machine-learning/models/README.md
      - LSTM: 05-machine-learning/models/lstm.md
      - Transformer: 05-machine-learning/models/transformer.md
      - Reinforcement Learning: 05-machine-learning/models/reinforcement-learning.md
      - Ensemble Methods: 05-machine-learning/models/ensemble-methods.md
      - Custom Models: 05-machine-learning/models/custom-models.md
    - Feature Engineering:
      - Overview: 05-machine-learning/feature-engineering/README.md
      - Technical Indicators: 05-machine-learning/feature-engineering/technical-indicators.md
      - Market Microstructure: 05-machine-learning/feature-engineering/market-microstructure.md
      - Sentiment Features: 05-machine-learning/feature-engineering/sentiment-features.md
      - Alternative Data: 05-machine-learning/feature-engineering/alternative-data.md
    - Training:
      - Overview: 05-machine-learning/training/README.md
      - Data Preparation: 05-machine-learning/training/data-preparation.md
      - Hyperparameter Tuning: 05-machine-learning/training/hyperparameter-tuning.md
      - Model Validation: 05-machine-learning/training/model-validation.md
      - Deployment: 05-machine-learning/training/deployment.md
    - Monitoring:
      - Overview: 05-machine-learning/monitoring/README.md
      - Model Drift: 05-machine-learning/monitoring/model-drift.md
      - Performance Tracking: 05-machine-learning/monitoring/performance-tracking.md
      - Alerts: 05-machine-learning/monitoring/alerts.md
  
  - Integrations:
    - Overview: 06-integrations/README.md
    - Exchanges:
      - Overview: 06-integrations/exchanges/README.md
      - Binance: 06-integrations/exchanges/binance.md
      - Coinbase: 06-integrations/exchanges/coinbase.md
      - Kraken: 06-integrations/exchanges/kraken.md
      - Bybit: 06-integrations/exchanges/bybit.md
      - Custom Exchange: 06-integrations/exchanges/custom-exchange.md
    - Data Providers:
      - Overview: 06-integrations/data-providers/README.md
      - Market Data: 06-integrations/data-providers/market-data.md
      - News Feeds: 06-integrations/data-providers/news-feeds.md
      - Social Media: 06-integrations/data-providers/social-media.md
      - On-Chain Data: 06-integrations/data-providers/on-chain-data.md
    - Notifications:
      - Overview: 06-integrations/notifications/README.md
      - Email: 06-integrations/notifications/email.md
      - Slack: 06-integrations/notifications/slack.md
      - Telegram: 06-integrations/notifications/telegram.md
      - Webhook: 06-integrations/notifications/webhook.md
    - External APIs:
      - Overview: 06-integrations/external-apis/README.md
      - Authentication: 06-integrations/external-apis/authentication.md
      - Rate Limiting: 06-integrations/external-apis/rate-limiting.md
      - Error Handling: 06-integrations/external-apis/error-handling.md
  
  - Operations:
    - Overview: 07-operations/README.md
    - Deployment:
      - Overview: 07-operations/deployment/README.md
      - Production: 07-operations/deployment/production.md
      - Staging: 07-operations/deployment/staging.md
      - Blue-Green: 07-operations/deployment/blue-green.md
      - Canary: 07-operations/deployment/canary.md
    - Monitoring:
      - Overview: 07-operations/monitoring/README.md
      - Prometheus: 07-operations/monitoring/prometheus.md
      - Grafana: 07-operations/monitoring/grafana.md
      - AlertManager: 07-operations/monitoring/alertmanager.md
      - Custom Metrics: 07-operations/monitoring/custom-metrics.md
    - Logging:
      - Overview: 07-operations/logging/README.md
      - Structured Logging: 07-operations/logging/structured-logging.md
      - Log Aggregation: 07-operations/logging/log-aggregation.md
      - Log Analysis: 07-operations/logging/log-analysis.md
    - Security:
      - Overview: 07-operations/security/README.md
      - Authentication: 07-operations/security/authentication.md
      - Authorization: 07-operations/security/authorization.md
      - Encryption: 07-operations/security/encryption.md
      - Secrets Management: 07-operations/security/secrets-management.md
      - Security Scanning: 07-operations/security/security-scanning.md
    - Backup:
      - Overview: 07-operations/backup/README.md
      - Database Backup: 07-operations/backup/database-backup.md
      - Configuration Backup: 07-operations/backup/configuration-backup.md
      - Disaster Recovery: 07-operations/backup/disaster-recovery.md
    - Scaling:
      - Overview: 07-operations/scaling/README.md
      - Horizontal Scaling: 07-operations/scaling/horizontal-scaling.md
      - Vertical Scaling: 07-operations/scaling/vertical-scaling.md
      - Auto Scaling: 07-operations/scaling/auto-scaling.md
      - Performance Tuning: 07-operations/scaling/performance-tuning.md
  
  - API Reference:
    - Overview: 08-api-reference/README.md
    - Authentication: 08-api-reference/authentication.md
    - Rate Limiting: 08-api-reference/rate-limiting.md
    - Error Codes: 08-api-reference/error-codes.md
    - Endpoints:
      - Trading: 08-api-reference/endpoints/trading.md
      - Analytics: 08-api-reference/endpoints/analytics.md
      - Strategies: 08-api-reference/endpoints/strategies.md
      - Portfolio: 08-api-reference/endpoints/portfolio.md
      - System: 08-api-reference/endpoints/system.md
    - Webhooks:
      - Overview: 08-api-reference/webhooks/README.md
      - Order Events: 08-api-reference/webhooks/order-events.md
      - Market Events: 08-api-reference/webhooks/market-events.md
      - System Events: 08-api-reference/webhooks/system-events.md
    - SDKs:
      - Overview: 08-api-reference/sdks/README.md
      - Python: 08-api-reference/sdks/python.md
      - JavaScript: 08-api-reference/sdks/javascript.md
      - Go: 08-api-reference/sdks/go.md
  
  - Tutorials:
    - Overview: 09-tutorials/README.md
    - Getting Started:
      - First Strategy: 09-tutorials/getting-started/first-strategy.md
      - Backtesting Tutorial: 09-tutorials/getting-started/backtesting-tutorial.md
      - Live Trading: 09-tutorials/getting-started/live-trading.md
    - Advanced:
      - Custom Indicators: 09-tutorials/advanced/custom-indicators.md
      - Machine Learning: 09-tutorials/advanced/machine-learning.md
      - Multi-Exchange: 09-tutorials/advanced/multi-exchange.md
      - Optimization: 09-tutorials/advanced/optimization.md
    - Case Studies:
      - Momentum Strategy: 09-tutorials/case-studies/momentum-strategy.md
      - Arbitrage Strategy: 09-tutorials/case-studies/arbitrage-strategy.md
      - Risk Management: 09-tutorials/case-studies/risk-management.md
    - Video Tutorials:
      - Overview: 09-tutorials/video-tutorials/README.md
      - Installation: 09-tutorials/video-tutorials/installation.md
      - Configuration: 09-tutorials/video-tutorials/configuration.md
      - Trading: 09-tutorials/video-tutorials/trading.md
  
  - Legal & Compliance:
    - Overview: 10-legal-compliance/README.md
    - Terms of Service: 10-legal-compliance/terms-of-service.md
    - Privacy Policy: 10-legal-compliance/privacy-policy.md
    - Disclaimer: 10-legal-compliance/disclaimer.md
    - Licenses:
      - Overview: 10-legal-compliance/licenses/README.md
      - MIT License: 10-legal-compliance/licenses/mit-license.md
      - Third Party: 10-legal-compliance/licenses/third-party.md
    - Regulations:
      - Overview: 10-legal-compliance/regulations/README.md
      - KYC/AML: 10-legal-compliance/regulations/kyc-aml.md
      - MiFID II: 10-legal-compliance/regulations/mifid-ii.md
      - CFTC: 10-legal-compliance/regulations/cftc.md
    - Audit:
      - Overview: 10-legal-compliance/audit/README.md
      - Security Audit: 10-legal-compliance/audit/security-audit.md
      - Compliance Audit: 10-legal-compliance/audit/compliance-audit.md
  
  - Community:
    - Overview: 11-community/README.md
    - Contributing: 11-community/contributing.md
    - Code of Conduct: 11-community/code-of-conduct.md
    - Governance: 11-community/governance.md
    - Roadmap: 11-community/roadmap.md
    - FAQ: 11-community/faq.md
    - Support: 11-community/support.md
    - Acknowledgments: 11-community/acknowledgments.md
  
  - Appendices:
    - Overview: 12-appendices/README.md
    - Glossary: 12-appendices/glossary.md
    - References: 12-appendices/references.md
    - Bibliography: 12-appendices/bibliography.md
    - Performance Benchmarks: 12-appendices/performance-benchmarks.md
    - System Requirements: 12-appendices/system-requirements.md
    - Version History: 12-appendices/version-history.md

# Plugin Configuration
plugins:
  # Core Plugins
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  
  # Minification
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
      cache_safe: true
  
  # Git Integration
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      timezone: UTC
      locale: en
      fallback_to_build_date: true
  
  - git-committers:
      repository: neural-crypto-bot/neural-crypto-bot-2.0
      branch: main
      enabled: !ENV [ENABLE_GIT_COMMITTERS, false]
  
  # Macros and Templates
  - macros:
      module_name: docs/macros
      include_dir: docs/templates
      include_yaml:
        - docs/data/config.yml
        - docs/data/performance.yml
  
  # Enhanced Navigation
  - awesome-pages:
      filename: .pages
      collapse_single_pages: true
      strict: false
  
  # Image Enhancement
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
  
  # API Documentation
  - swagger-ui-tag:
      background: White
      syntaxHighlightTheme: monokai
  
  # Code Documentation
  - gen-files:
      scripts:
      - scripts/docs/gen_ref_pages.py
  
  - literate-nav:
      nav_file: SUMMARY.md
  
  - section-index
  
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_object_full_path: false
            show_category_heading: true
            show_if_no_docstring: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            merge_init_into_class: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            members_order: source
            group_by_category: true
            heading_level: 2
  
  # URL Redirects
  - redirects:
      redirect_maps:
        'old-docs.md': 'index.md'
        'legacy/api.md': '08-api-reference/README.md'
  
  # File Exclusion
  - exclude:
      glob:
        - "*.tmp"
        - "*.py[co]"
        - "__pycache__"
        - ".DS_Store"

# Markdown Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  
  # PyMdown Extensions
  - pymdownx.arithmatex:
      generic: true
  
  - pymdownx.betterem:
      smart_enable: all
  
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  
  - pymdownx.critic:
      mode: view
  
  - pymdownx.details
  
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
      linenums: false
      linenums_style: table
  
  - pymdownx.inlinehilite
  
  - pymdownx.keys
  
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: neural-crypto-bot
      repo: neural-crypto-bot-2.0
      normalize_issue_symbols: true
  
  - pymdownx.smartsymbols
  
  - pymdownx.snippets:
      base_path: 
        - docs/templates
        - docs/examples
      check_paths: true
      dedent_subsections: true
  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  
  - pymdownx.tasklist:
      custom_checkbox: true
  
  - pymdownx.progressbar

# Extra Configuration
extra:
  # Analytics
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/neural-crypto-bot/neural-crypto-bot-2.0/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">telling us what you're looking for</a>.
  
  # Social Links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/neural-crypto-bot/neural-crypto-bot-2.0
      name: GitHub Repository
    - icon: fontawesome/brands/discord
      link: https://discord.gg/neural-crypto-bot
      name: Discord Community
    - icon: fontawesome/brands/telegram
      link: https://t.me/neural_crypto_bot
      name: Telegram Channel
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/neuralcryptobot
      name: Twitter Updates
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@neuralcryptobot
      name: YouTube Tutorials
    - icon: fontawesome/brands/reddit
      link: https://reddit.com/r/neuralcryptobot
      name: Reddit Community
  
  # Versioning
  version:
    provider: mike
    default: latest
    alias: true
  
  # Generator Notice
  generator: false
  
  # Status
  status:
    new: Recently added
    deprecated: Deprecated
  
  # Tags
  tags:
    Trading: trading
    Machine Learning: ml
    API: api
    Tutorial: tutorial
    Advanced: advanced
  
  # Cookie Consent
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
    cookies:
      analytics:
        name: Google Analytics
        checked: false
      github:
        name: GitHub
        checked: false

# Additional JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/feedback.js
  - javascripts/shortcuts.js
  - javascripts/copy-code.js
  - javascripts/external-links.js

# Additional CSS
extra_css:
  - stylesheets/extra.css
  - stylesheets/ncb-theme.css
  - stylesheets/api-styles.css
  - stylesheets/print.css

# Validation
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

# Watch for Changes (Development)
watch:
  - src/
  - scripts/docs/
  - mkdocs.yml
EOF
    
    log_success "Configuração principal do MkDocs criada: mkdocs.yml"
    
    # Verificar se o arquivo foi criado corretamente
    if [[ -f "$MKDOCS_CONFIG_FILE" ]]; then
        local line_count
        line_count=$(wc -l < "$MKDOCS_CONFIG_FILE")
        log_info "Arquivo criado com $line_count linhas"
        
        # Validar sintaxe YAML básica
        if python3 -c "import yaml; yaml.safe_load(open('$MKDOCS_CONFIG_FILE'))" 2>/dev/null; then
            log_success "Sintaxe YAML validada"
        else
            log_warning "Possível problema na sintaxe YAML"
        fi
        
        return 0
    else
        log_error "Falha ao criar arquivo de configuração"
        return 1
    fi
}

# ================================
# FUNÇÃO AUXILIAR
# ================================

verify_mkdocs_structure() {
    local issues=()
    
    # Verificar seções obrigatórias
    local required_sections=(
        "site_name"
        "theme"
        "nav"
        "plugins"
        "markdown_extensions"
    )
    
    for section in "${required_sections[@]}"; do
        if ! grep -q "^$section:" "$MKDOCS_CONFIG_FILE"; then
            issues+=("Seção ausente: $section")
        fi
    done
    
    # Verificar tema Material
    if ! grep -q "name: material" "$MKDOCS_CONFIG_FILE"; then
        issues+=("Tema Material não configurado")
    fi
    
    # Verificar plugins essenciais
    local essential_plugins=("search" "minify" "macros")
    for plugin in "${essential_plugins[@]}"; do
        if ! grep -q "- $plugin" "$MKDOCS_CONFIG_FILE"; then
            issues+=("Plugin essencial ausente: $plugin")
        fi
    done
    
    if [[ ${#issues[@]} -gt 0 ]]; then
        log_warning "Problemas encontrados na estrutura:"
        for issue in "${issues[@]}"; do
            log_warning "  • $issue"
        done
        return 1
    fi
    
    return 0
}