global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Sem alertmanagers por enquanto

rule_files:
  # Sem regras por enquanto

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'neural-crypto-bot'
    static_configs:
      - targets: ['api:8000', 'execution:8080', 'collector:8080', 'training:8080']
